In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {(829,827,1,2.05,4.14,4.14,10.1,15.2),
(829,821,4,6.63,13.26,13.26,32.4,48.5),
(829,804,7,14.41,28.92,28.92,64.7,97),
(829,822,6,5.9,11.81,11.81,28.8,43.2),
(829,826,9,2.87,5.81,5.81,14.2,21.2),
(829,807,2,9.81,19.62,19.62,46,69),
(829,809,4,7.91,15.72,15.72,38.4,57.5),
(829,801,1,18.21,36.32,36.32,79.5,119.2),
(829,824,7,8.77,21.4,21.4,32.1,4.35),
(829,823,4,5,10,10,24.4,36.6),
(829,831,9,1.72,3.36,3.36,8.3,12.4),
(829,808,5,8.51,16.92,16.92,40.7,61),
(829,802,5,16.91,33.72,33.72,74.3,111.4),
(829,805,3,12.41,24.82,24.82,56.5,84.7),
(829,825,2,3.69,7.46,7.46,18.2,27.3),
(829,806,9,11.61,23.22,23.22,53.4,80),
(829,830,7,1.23,2.38,2.38,5.9,8.8),
(829,803,2,15.21,30.52,30.52,67.9,101.8),
(827,829,10,2.05,4.14,4.14,10.1,15.2),
(827,821,9,4.73,9.43,9.43,23.1,34.6),
(827,804,9,12.52,25.13,25.13,55.4,83.1),
(827,822,9,4,8,8,19.5,29.3),
(827,826,2,1.07,2.05,2.05,5,7.5),
(827,807,1,7.92,15.83,15.83,36.7,55.1),
(827,809,8,6.02,11.93,11.93,29.1,43.6),
(827,801,9,16.32,32.53,32.53,70.2,105.3),
(827,824,9,2.46,4.92,4.92,12.1,18.1),
(827,823,3,3.09,6.15,6.15,15.1,22.6),
(827,831,2,3.52,7.04,7.04,17.2,25.7),
(827,808,10,6.62,13.13,13.13,31.4,47.1),
(827,802,4,15.02,29.93,29.93,65,97.5),
(827,805,2,10.52,21.03,21.03,47.2,70.8),
(827,825,2,1.8,3.65,3.65,8.9,13.4),
(827,806,4,9.72,19.43,19.43,44.1,66.1),
(827,830,8,3.03,6.06,6.06,14.8,22.2),
(827,803,7,13.32,26.73,26.73,58.6,101.8),
(821,829,3,6.63,13.26,13.26,32.4,48.5),
(821,827,3,4.73,9.43,9.43,23.1,34.6),
(821,804,1,8.01,16.12,16.12,33.3,50),
(821,822,5,0.9,1.8,1.8,4.4,6.7),
(821,826,8,4,8.01,8.01,19.5,29.3),
(821,807,6,3.41,6.82,7.97,14.6,22),
(821,809,3,1.51,2.92,2.92,7,10.5),
(821,801,6,11.81,23.52,23.52,48.1,72.2),
(821,824,4,2.53,5.06,5.06,12.3,18.5),
(821,823,2,1.8,3.67,3.67,9,13.4),
(821,831,8,8.08,16.15,16.15,39.4,59.1),
(821,808,3,2.11,4.12,4.12,9.3,14),
(821,802,1,10.51,20.92,20.92,42.9,64.4),
(821,805,6,6.01,12.02,12.02,25.1,37.7),
(821,825,7,3.11,6.22,6.22,15.2,22.8),
(821,806,3,5.21,10.42,10.42,22,33),
(821,830,3,7.59,15.17,15.17,37,55.5),
(821,803,7,8.81,17.72,17.72,36.5,54.8),
(804,829,10,14.41,28.92,28.92,64.7,97),
(804,827,3,12.52,25.13,25.13,55.4,83.1),
(804,821,3,8.01,16.12,16.12,33.3,50),
(804,822,5,8.59,17.27,17.27,36.2,54.3),
(804,826,1,11.68,23.47,23.47,51.3,77),
(804,807,1,4.8,9.5,9.5,19,28.6),
(804,809,5,6.8,13.7,13.7,27.4,41.1),
(804,801,10,3.9,7.7,7.7,15.4,23.1),
(804,824,10,10.21,20.52,20.52,44.1,66.2),
(804,823,9,9.49,19.13,19.13,40.7,61.1),
(804,831,3,15.87,31.84,31.84,71.7,107.6),
(804,808,6,6.1,12.3,12.3,24.6,36.8),
(804,802,6,2.6,5.2,5.2,10.3,15.5),
(804,805,1,2.2,4.4,4.4,8.8,13.2),
(804,825,3,10.79,21.68,21.68,46.9,70.4),
(804,806,5,3,6.1,6.1,12.2,18.2),
(804,830,8,15.38,30.87,30.87,69.4,104),
(804,803,5,1,2,2,3.9,5.9),
(822,829,8,5.9,11.81,11.81,28.8,43.2),
(822,827,2,4,8,8,19.5,29.3),
(822,821,8,0.9,1.8,1.8,4.4,6.7),
(822,804,2,8.59,17.27,17.27,36.2,54.3),
(822,826,3,3.28,6.55,6.55,16,24),
(822,807,1,3.99,7.97,7.97,17.5,26.3),
(822,809,9,2.09,4.07,4.07,9.9,14.8),
(822,801,3,12.39,24.67,24.67,51,76.5),
(822,824,9,1.8,3.6,3.6,8.8,13.2),
(822,823,3,1.15,2.21,2.21,5.4,8.1),
(822,831,4,7.36,14.68,14.68,35.9,53.8),
(822,808,4,2.69,5.27,5.27,12.2,18.3),
(822,802,10,11.09,22.07,22.07,45.8,68.7),
(822,805,5,6.59,13.17,13.17,28,42),
(822,825,5,2.38,4.76,4.76,11.6,17.4),
(822,806,6,5.79,11.57,11.57,24.9,37.3),
(822,830,10,6.87,13.74,13.74,33.5,50.3),
(822,803,5,9.39,18.87,18.87,39.4,59.1),
(826,829,2,2.87,5.81,5.81,14.2,21.2),
(826,827,10,1.07,2.05,2.05,5,7.5),
(826,821,2,4,8.01,8.01,19.5,29.3),
(826,804,7,11.68,23.47,23.47,51.3,77),
(826,822,7,3.28,6.55,6.55,16,24),
(826,807,10,7.08,14.17,14.17,32.6,49),
(826,809,10,5.18,10.27,10.27,25,37.5),
(826,801,4,15.48,30.87,30.87,66.1,99.2),
(826,824,8,1.72,3.5,3.5,8.5,12.8),
(826,823,6,2.37,4.74,4.74,11.6,17.4),
(826,831,9,4.35,8.69,8.69,21.2,31.8),
(826,808,3,5.78,11.47,11.47,27.3,41),
(826,802,6,14.18,28.27,28.27,60.9,91.4),
(826,805,2,9.68,19.37,19.37,43.1,64.7),
(826,825,10,1.07,2.2,2.2,5.4,8.1),
(826,806,8,8.88,17.77,17.77,40,60),
(826,830,2,3.85,7.71,7.71,18.8,28.2),
(826,803,7,12.48,25.07,25.07,54.5,81.8),
(807,829,5,9.81,19.62,19.62,46,69),
(807,827,8,7.92,15.83,15.83,36.7,55.1),
(807,821,3,3.41,6.82,6.82,14.6,22),
(807,804,8,4.8,9.5,9.5,19,28.6),
(807,822,10,3.99,7.97,7.97,17.5,26.3),
(807,826,3,7.08,14.17,14.17,32.6,49),
(807,809,6,2.2,4.3,4.3,8.7,13),
(807,801,1,8.4,16.9,16.9,33.7,50.6),
(807,824,2,5.61,11.22,11.22,25.4,38.2),
(807,823,8,4.89,9.83,9.83,22,33.1),
(807,831,6,11.27,22.54,22.54,53,79.6),
(807,808,2,1.5,2.9,2.9,5.8,8.8),
(807,802,10,7.2,14.3,14.3,28.6,42.9),
(807,805,10,2.7,5.4,5.4,10.8,16.3),
(807,825,5,6.19,12.38,12.38,28.2,42.4),
(807,806,4,1.9,3.8,3.8,7.7,11.5),
(807,830,6,10.78,21.57,21.57,50.7,76),
(807,803,6,5.6,11.1,11.1,22.2,33.3),
(809,829,9,7.91,15.72,15.72,38.4,57.5),
(809,827,1,6.02,11.93,11.93,29.1,43.6),
(809,821,8,1.51,2.92,2.92,7,10.5),
(809,804,3,6.8,13.7,13.7,27.4,41.1),
(809,822,6,2.09,4.07,4.07,9.9,14.8),
(809,826,2,5.18,10.27,10.27,25,37.5),
(809,807,4,2.2,4.3,4.3,8.7,13),
(809,801,6,10.5,21,21,42.1,63.1),
(809,824,4,3.71,7.32,7.32,17.8,26.7),
(809,823,8,2.99,5.93,5.93,14.4,21.6),
(809,831,1,9.37,18.64,18.64,45.4,68.1),
(809,808,3,0.8,1.7,1.7,3.3,5),
(809,802,7,9.2,18.5,18.5,37,55.4),
(809,805,10,4.8,9.6,9.6,19.2,28.8),
(809,825,1,4.29,8.48,8.48,20.6,30.9),
(809,806,5,4,8,8,16,24),
(809,830,3,8.88,17.67,17.67,43.1,64.5),
(809,803,1,7.6,15.3,15.3,30.6,45.8),
(801,829,8,18.21,36.32,36.32,79.5,119.2),
(801,827,3,16.32,32.53,32.53,70.2,105.3),
(801,821,2,11.81,23.52,23.52,48.1,72.2),
(801,804,3,3.9,7.7,7.7,15.4,23.1),
(801,822,4,12.39,24.67,24.67,51,76.5),
(801,826,1,15.48,30.87,30.87,66.1,99.2),
(801,807,9,8.4,16.9,16.9,33.7,50.6),
(801,809,1,10.5,21,21,42.1,63.1),
(801,824,6,14.01,27.92,27.92,58.9,88.4),
(801,823,8,13.29,26.53,26.53,55.5,83.3),
(801,831,4,19.67,39.24,39.24,86.5,129.8),
(801,808,6,9.8,19.6,19.6,39.2,58.9),
(801,802,1,1.4,2.8,2.8,5.5,8.3),
(801,805,8,5.9,11.7,11.7,23.5,35.2),
(801,825,9,14.59,29.08,29.08,61.7,92.6),
(801,806,5,6.7,13.4,13.4,26.8,40.3),
(801,830,9,19.18,38.27,38.27,84.2,126.2),
(801,803,5,3,6,6,6.9,18),
(824,829,4,4.35,8.77,8.77,21.4,32.1),
(824,827,3,2.46,4.92,4.92,12.1,18.1),
(824,821,2,2.53,5.06,5.06,12.3,18.5),
(824,804,3,10.21,20.52,20.52,44.1,66.2),
(824,822,10,1.8,3.6,3.6,8.8,13.2),
(824,826,6,1.72,3.5,3.5,8.5,12.8),
(824,807,6,5.61,11.22,11.22,25.4,38.2),
(824,809,4,3.71,7.32,7.32,17.8,26.7),
(824,801,6,14.01,27.92,27.92,58.9,88.4),
(824,823,1,0.9,1.79,1.79,4.4,6.6),
(824,831,5,5.82,11.64,11.64,28.4,42.7),
(824,808,7,4.31,8.52,8.52,20.1,30.2),
(824,802,7,12.71,25.32,25.32,53.7,80.6),
(824,805,5,8.21,16.42,16.42,35.9,53.9),
(824,825,1,0.82,1.71,1.71,4.2,6.3),
(824,806,2,7.41,7.8,14.82,32.8,49.2),
(824,830,4,5.33,10.66,10.66,26,39.1),
(824,803,1,11.01,22.12,22.12,47.3,71),
(823,829,7,5,10,10,24.4,36.6),
(823,827,1,3.09,6.15,6.15,15.1,22.6),
(823,821,2,1.8,3.67,3.67,9,13.4),
(823,804,10,9.49,19.13,19.13,40.7,61.1),
(823,822,6,1.15,2.21,2.21,5.4,8.1),
(823,826,7,2.37,4.74,4.74,11.6,17.4),
(823,807,3,4.89,9.83,9.83,22,33.1),
(823,809,5,2.99,5.93,5.93,14.4,21.6),
(823,801,1,13.29,26.53,26.53,55.5,83.3),
(823,824,9,0.9,1.79,1.79,4.4,6.6),
(823,831,4,6.45,12.87,12.87,31.4,47.2),
(823,808,5,3.59,7.13,7.13,16.7,25.1),
(823,802,4,11.99,23.93,23.93,50.3,75.5),
(823,805,3,7.49,15.03,15.03,32.5,48.8),
(823,825,4,1.47,2.94,2.94,7.2,10.8),
(823,806,8,6.69,13.43,13.43,29.4,44.1),
(823,830,5,5.96,11.89,11.89,29.1,43.6),
(823,803,3,10.29,20.73,20.73,43.9,65.9),
(831,829,6,1.72,3.36,3.36,8.3,12.4),
(831,827,10,3.52,7.04,7.04,17.2,25.7),
(831,821,9,8.08,16.15,16.15,39.4,59.1),
(831,804,9,15.87,31.84,31.84,71.7,107.6),
(831,822,6,7.36,14.68,14.68,35.9,53.8),
(831,826,7,4.35,8.69,8.69,21.2,31.8),
(831,807,1,11.27,22.54,22.54,53,79.6),
(831,809,9,9.37,18.64,18.64,45.4,68.1),
(831,801,2,19.67,39.24,39.24,86.5,129.8),
(831,824,3,5.82,11.64,11.64,28.4,42.7),
(831,823,5,6.45,12.87,12.87,31.4,47.2),
(831,808,6,9.97,19.84,19.84,47.7,71.6),
(831,802,7,18.37,36.64,36.64,81.3,122),
(831,805,9,13.87,27.74,27.74,63.5,95.3),
(831,825,6,5.17,10.33,10.33,25.2,37.9),
(831,806,5,13.07,26.14,26.14,60.4,90.6),
(831,830,1,0.74,1.39,1.39,3.5,5.2),
(831,803,6,16.67,33.44,33.44,74.9,112.4),
(808,829,5,8.51,16.92,16.92,40.7,61),
(808,827,1,6.62,13.13,13.13,31.4,47.1),
(808,821,6,2.11,4.12,4.12,9.3,14),
(808,804,5,6.1,12.3,12.3,24.6,36.8),
(808,822,3,2.69,5.27,5.27,12.2,18.3),
(808,826,9,5.78,11.47,11.47,27.3,41),
(808,807,2,1.5,2.9,2.9,5.8,8.8),
(808,809,9,0.8,1.7,1.7,3.3,5),
(808,801,3,9.8,19.6,19.6,39.2,58.9),
(808,824,1,4.31,8.52,8.52,20.1,30.2),
(808,823,7,3.59,7.13,7.13,16.7,25.1),
(808,831,4,9.97,19.84,19.84,47.7,71.6),
(808,802,5,8.5,17.1,17.1,34.1,51.2),
(808,805,2,4.1,8.2,8.2,16.4,24.5),
(808,825,4,4.89,9.68,9.68,22.9,34.4),
(808,806,10,3.3,6.6,6.6,13.2,19.8),
(808,830,4,9.48,18.87,18.87,45.4,68),
(808,803,7,6.9,13.9,13.9,27.7,41.6),
(802,829,9,16.91,33.72,33.72,74.3,111.4),
(802,827,7,15.02,29.93,29.93,65,97.5),
(802,821,10,10.51,20.92,20.92,42.9,64.4),
(802,804,6,2.6,5.2,5.2,10.3,15.5),
(802,822,4,11.09,22.07,22.07,45.8,68.7),
(802,826,1,14.18,28.27,28.27,60.9,91.4),
(802,807,7,7.2,14.3,14.3,28.6,42.9),
(802,809,1,9.2,18.5,18.5,37,55.4),
(802,801,8,1.4,2.8,2.8,5.5,8.3),
(802,824,10,12.71,25.32,25.32,53.7,80.6),
(802,823,2,11.99,23.93,23.93,50.3,75.5),
(802,831,1,18.37,36.64,36.64,81.3,122),
(802,808,3,8.5,17.1,17.1,34.1,51.2),
(802,805,4,4.6,9.2,9.2,18.4,27.6),
(802,825,6,13.29,26.48,26.48,55.9,84.8),
(802,806,6,5.4,10.9,10.9,21.7,32.6),
(802,830,3,17.88,35.67,35.67,79,118.4),
(802,803,2,1.7,3.4,3.4,6.9,10.3),
(805,829,7,12.41,24.82,24.82,56.5,84.7),
(805,827,4,10.52,21.03,21.03,47.2,70.8),
(805,821,9,6.01,12.02,12.02,25.1,37.7),
(805,804,10,2.2,4.4,4.4,8.8,13.2),
(805,822,2,6.59,13.17,13.17,28,42),
(805,826,2,9.68,19.37,19.37,43.1,64.7),
(805,807,10,2.7,5.4,5.4,10.8,16.3),
(805,809,9,4.8,9.6,9.6,19.2,28.8),
(805,801,9,5.9,11.7,11.7,23.5,35.2),
(805,824,5,8.21,16.42,16.42,35.9,53.9),
(805,823,7,7.49,15.03,15.03,32.5,48.8),
(805,831,8,13.87,27.74,27.74,63.5,95.3),
(805,808,2,4.1,8.2,8.2,16.4,24.5),
(805,802,5,4.6,9.2,9.2,18.4,27.6),
(805,825,5,8.79,17.58,17.58,38.7,58.1),
(805,806,1,1,2,2,4,5.9),
(805,830,5,13.38,26.77,26.77,61.2,91.7),
(805,803,1,3,6,6,12,17.9),
(825,829,2,3.69,7.46,7.46,18.2,27.3),
(825,827,9,1.8,3.65,3.65,8.9,13.4),
(825,821,1,3.11,6.22,6.22,15.2,22.8),
(825,804,2,10.79,21.68,21.68,46.9,70.4),
(825,822,8,2.38,4.76,4.76,11.6,17.4),
(825,826,6,1.07,2.2,2.2,5.4,8.1),
(825,807,1,6.19,12.38,12.38,28.2,42.4),
(825,809,6,4.29,8.48,8.48,20.6,30.9),
(825,801,6,14.59,29.08,29.08,61.7,92.6),
(825,824,3,0.82,1.71,1.71,4.2,6.3),
(825,823,6,1.47,2.94,2.94,7.2,10.8),
(825,831,9,5.17,10.33,10.33,25.2,37.9),
(825,808,8,4.89,9.68,9.68,22.9,34.4),
(825,802,1,13.29,26.48,26.48,56.5,84.8),
(825,805,8,8.79,17.58,17.58,38.7,58.1),
(825,806,7,7.99,15.98,15.98,35.6,53.4),
(825,830,3,4.67,9.35,9.35,22.9,34.3),
(825,803,10,11.59,23.28,23.28,50.1,75.2),
(806,829,9,11.61,23.22,23.22,53.4,80),
(806,827,5,9.72,19.43,19.43,44.1,66.1),
(806,821,10,5.21,10.42,10.42,22,33),
(806,804,1,3,6.1,6.1,12.2,18.2),
(806,822,7,5.79,11.57,11.57,24.9,37.3),
(806,826,10,8.88,17.77,17.77,40,60),
(806,807,1,1.9,3.8,3.8,7.7,11.5),
(806,809,10,4,8,8,16,24),
(806,801,7,6.7,13.4,13.4,26.8,40.3),
(806,824,6,7.41,14.82,14.82,32.8,49.2),
(806,823,5,6.69,13.43,13.43,29.4,44.1),
(806,831,9,13.07,26.14,26.14,60.4,90.6),
(806,808,8,3.3,6.6,6.6,13.2,19.8),
(806,802,10,5.4,10.9,10.9,21.7,32.6),
(806,805,5,1,2,2,4,5.9),
(806,825,2,7.99,15.98,15.98,35.6,53.4),
(806,830,6,12.58,25.17,25.17,58.1,87),
(806,803,7,3.8,7.7,7.7,15.3,23),
(830,829,6,1.23,2.38,2.38,5.9,8.8),
(830,827,8,3.03,6.06,6.06,14.8,22.2),
(830,821,7,7.59,15.17,15.17,37,55.5),
(830,804,9,15.38,30.87,30.87,69.4,104),
(830,822,10,6.87,13.74,13.74,33.5,50.3),
(830,826,10,3.85,7.71,7.71,18.8,28.2),
(830,807,4,10.78,21.57,21.57,50.7,76),
(830,809,8,8.88,17.67,17.67,43.1,64.5),
(830,801,9,19.18,38.27,30.27,84.2,126.2),
(830,824,4,5.33,10.66,10.66,26,39.1),
(830,823,5,5.96,11.89,11.89,29.1,43.6),
(830,831,5,0.74,1.39,1.39,3.5,5.2),
(830,808,6,9.48,18.87,18.87,45.4,68),
(830,802,8,17.88,35.67,35.67,79,118.4),
(830,805,6,13.38,26.77,26.77,61.2,91.7),
(830,806,3,12.58,25.17,25.17,58.1,87),
(830,803,7,16.18,32.47,32.47,72.6,108.8),
(803,829,10,15.21,30.52,30.52,67.9,101.8),
(803,827,6,13.32,26.73,26.73,58.6,87.9),
(803,821,1,8.81,17.72,17.72,36.5,54.8),
(803,804,9,1,2,2,3.9,5.9),
(803,822,4,9.39,18.87,18.87,39.4,59.1),
(803,826,3,12.48,25.07,25.07,54.5,81.8),
(803,807,5,5.6,11.1,11.1,22.2,33.3),
(803,809,5,7.6,15.3,15.3,30.6,45.8),
(803,801,7,3,6,6,12,18),
(803,824,1,11.01,22.12,22.12,47.3,71),
(803,823,4,10.29,20.73,20.73,43.9,65.9),
(803,831,3,16.67,33.44,33.44,74.9,112.4),
(803,808,8,6.9,13.9,13.9,27.7,41.6),
(803,802,3,1.7,3.4,3.4,6.9,10.3),
(803,805,4,3,6,6,12,17.9),
(803,825,3,11.59,23.28,23.28,50.1,75.2),
(803,806,9,3.8,7.7,7.7,15.3,23),
(803,830,1,16.18,32.47,32.47,72.6,108.8)}

In [4]:
df=pd.DataFrame(data=data,columns=['id_1','id_2','route','moto','car','rv','bus','truck'])

In [5]:
df.head()

   id_1  id_2  route   moto    car     rv   bus  truck
0   830   829      6   1.23   2.38   2.38   5.9    8.8
1   808   821      6   2.11   4.12   4.12   9.3   14.0
2   802   822      4  11.09  22.07  22.07  45.8   68.7
3   821   826      8   4.00   8.01   8.01  19.5   29.3
4   830   824      4   5.33  10.66  10.66  26.0   39.1

### Question 1: Car Matrix Generation

In [21]:
#Under the function named generate_car_matrix write a logic that takes the dataset-1.csv as a DataFrame. 
#Return a new DataFrame that follows the following rules:
#values from id_2 as columns
#values from id_1 as index
#dataframe should have values from car column
#diagonal values should be 0.

In [15]:
def generate_car_matrix(df):
    result_df = df.pivot(index='id_1', columns='id_2', values='car')
    np.fill_diagonal(result_df.values, 0)
    return result_df

In [7]:
generate_car_matrix(df)

id_2,801,802,803,804,805,806,807,808,809,821,822,823,824,825,826,827,829,830,831
id_1,,,,,,,,,,,,,,,,,,,
801,0.00,2.80,6.00,7.70,11.70,13.40,16.90,19.60,21.00,23.52,24.67,26.53,27.92,29.08,30.87,32.53,36.32,38.27,39.24
802,2.80,0.00,3.40,5.20,9.20,10.90,14.30,17.10,18.50,20.92,22.07,23.93,25.32,26.48,28.27,29.93,33.72,35.67,36.64
803,6.00,3.40,0.00,2.00,6.00,7.70,11.10,13.90,15.30,17.72,18.87,20.73,22.12,23.28,25.07,26.73,30.52,32.47,33.44
804,7.70,5.20,2.00,0.00,4.40,6.10,9.50,12.30,13.70,16.12,17.27,19.13,20.52,21.68,23.47,25.13,28.92,30.87,31.84
805,11.70,9.20,6.00,4.40,0.00,2.00,5.40,8.20,9.60,12.02,13.17,15.03,16.42,17.58,19.37,21.03,24.82,26.77,27.74
806,13.40,10.90,7.70,6.10,2.00,0.00,3.80,6.60,8.00,10.42,11.57,13.43,14.82,15.98,17.77,19.43,23.22,25.17,26.14
807,16.90,14.30,11.10,9.50,5.40,3.80,0.00,2.90,4.30,6.82,7.97,9.83,11.22,12.38,14.17,15.83,19.62,21.57,22.54
808,19.60,17.10,13.90,12.30,8.20,6.60,2.90,0.00,1.70,4.12,5.27,7.13,8.52,9.68,11.47,13.13,16.92,18.87,19.84
809,21.00,18.50,15.30,13.70,9.60,8.00,4.30,1.70,0.00,2.92,4.07,5.93,7.32,8.48,10.27,11.93,15.72,17.67,18.64
821,23.52,20.92,17.72,16.12,12.02,10.42,6.82,4.12,2.92,0.00,1.80,3.67,5.06,6.22,8.01,9.43,13.26,15.17,16.15
822,24.67,22.07,18.87,17.27,13.17,11.57,7.97,5.27,4.07,1.80,0.00,2.21,3.60,4.76,6.55,8.00,11.81,13.74,14.68
823,26.53,23.93,20.73,19.13,15.03,13.43,9.83,7.13,5.93,3.67,2.21,0.00,1.79,2.94,4.74,6.15,10.00,11.89,12.87
824,27.92,25.32,22.12,20.52,16.42,7.80,11.22,8.52,7.32,5.06,3.60,1.79,0.00,1.71,3.50,4.92,8.77,10.66,11.64
825,29.08,26.48,23.28,21.68,17.58,15.98,12.38,9.68,8.48,6.22,4.76,2.94,1.71,0.00,2.20,3.65,7.46,9.35,10.33
826,30.87,28.27,25.07,23.47,19.37,17.77,14.17,11.47,10.27,8.01,6.55,4.74,3.50,2.20,0.00,2.05,5.81,7.71,8.69
827,32.53,29.93,26.73,25.13,21.03,19.43,15.83,13.13,11.93,9.43,8.00,6.15,4.92,3.65,2.05,0.00,4.14,6.06,7.04
829,36.32,33.72,30.52,28.92,24.82,23.22,19.62,16.92,15.72,13.26,11.81,10.00,21.40,7.46,5.81,4.14,0.00,2.38,3.36
830,38.27,35.67,32.47,30.87,26.77,25.17,21.57,18.87,17.67,15.17,13.74,11.89,10.66,NaN,7.71,6.06,2.38,0.00,1.39
831,39.24,36.64,33.44,31.84,27.74,26.14,22.54,19.84,18.64,16.15,14.68,12.87,11.64,10.33,8.69,7.04,3.36,1.39,0.00

### Question 2: Car Type Count Calculation

In [9]:
#Create a Python function named get_type_count that takes the dataset-1.csv as a DataFrame. 
#Add a new categorical column car_type based on values of the column car:

#low for values less than or equal to 15,
#medium for values greater than 15 and less than or equal to 25,
#high for values greater than 25.
#Calculate the count of occurrences for each car_type category and return the result as a dictionary. 
#Sort the dictionary alphabetically based on keys.

In [8]:
df['car_type'] = np.where(df['car'] <= 15, 'low', 
                              np.where(df['car'] <= 25, 'medium', 'high'))

In [9]:
df

     id_1  id_2  route   moto    car     rv   bus  truck car_type
0     830   829      6   1.23   2.38   2.38   5.9    8.8      low
1     808   821      6   2.11   4.12   4.12   9.3   14.0      low
2     802   822      4  11.09  22.07  22.07  45.8   68.7   medium
3     821   826      8   4.00   8.01   8.01  19.5   29.3      low
4     830   824      4   5.33  10.66  10.66  26.0   39.1      low
..    ...   ...    ...    ...    ...    ...   ...    ...      ...
336   806   807      1   1.90   3.80   3.80   7.7   11.5      low
337   823   802      4  11.99  23.93  23.93  50.3   75.5   medium
338   823   830      5   5.96  11.89  11.89  29.1   43.6      low
339   823   803      3  10.29  20.73  20.73  43.9   65.9   medium
340   822   831      4   7.36  14.68  14.68  35.9   53.8      low

[341 rows x 9 columns]

In [16]:
def get_type_count(df):
    df['car_type'] = np.where(df['car'] <= 15, 'low', 
                              np.where(df['car'] <= 25, 'medium', 'high'))
    
    type_count = df['car_type'].value_counts().to_dict()
    type_count = dict(sorted(type_count.items()))
    
    return type_count

In [17]:
get_type_count(df)

{'high': 56, 'low': 196, 'medium': 89}

### Question 3: Bus Count Index Retrieval

In [22]:
#Create a Python function named get_bus_indexes that takes the dataset-1.csv as a DataFrame. 
#The function should identify and return the indices as a list (sorted in ascending order) 
#where the bus values are greater than twice the mean value of the bus column in the DataFrame.

In [18]:
def get_bus_indexes(df):
    threshold = 2 * df['bus'].mean()
    indices = df[df['bus'] > threshold].index.tolist()
    indices.sort()
    
    return indices

In [13]:
get_bus_indexes(df)

[26,
 28,
 39,
 40,
 56,
 59,
 65,
 77,
 80,
 83,
 92,
 98,
 100,
 106,
 128,
 139,
 143,
 145,
 156,
 167,
 172,
 192,
 215,
 223,
 224,
 233,
 257,
 262,
 302,
 334]

### Question 4: Route Filtering

In [25]:
#Create a python function filter_routes that takes the dataset-1.csv as a DataFrame. 
#The function should return the sorted list of values of column route for which the average of values of 
#truck column is greater than 7.

In [19]:
def filter_routes(df):
    avg_truck = df.groupby('route')['truck'].mean()
    routes = avg_truck[avg_truck > 7].index.tolist()

    routes.sort()
    
    return routes 
routes = filter_routes(df)

In [45]:
routes

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### Question 5: Matrix Value Modification

In [26]:
#Create a Python function named multiply_matrix that takes the resulting DataFrame from Question 1,
#as input and modifies each value according to the following logic:

#If a value in the DataFrame is greater than 20, multiply those values by 0.75,
#If a value is 20 or less, multiply those values by 1.25.
#The function should return the modified DataFrame which has values rounded to 1 decimal place.

In [40]:
def multiply_matrix(df):
    df = df.apply(pd.to_numeric, errors='coerce')
    df = df.applymap(lambda x: x * 0.75 if x > 20 else x * 1.25 if np.isfinite(x) else x)
    df = df.round(1)
    return df
new_df=multiply_matrix(df)

In [41]:
new_df

      id_1   id_2  route  moto   car    rv   bus  truck  car_type
0    622.5  621.8    7.5   1.5   3.0   3.0   7.4   11.0       NaN
1    606.0  615.8    7.5   2.6   5.2   5.2  11.6   17.5       NaN
2    601.5  616.5    5.0  13.9  16.6  16.6  34.3   51.5       NaN
3    615.8  619.5   10.0   5.0  10.0  10.0  24.4   22.0       NaN
4    622.5  618.0    5.0   6.7  13.3  13.3  19.5   29.3       NaN
..     ...    ...    ...   ...   ...   ...   ...    ...       ...
336  604.5  605.2    1.2   2.4   4.8   4.8   9.6   14.4       NaN
337  617.2  601.5    5.0  15.0  17.9  17.9  37.7   56.6       NaN
338  617.2  622.5    6.2   7.4  14.9  14.9  21.8   32.7       NaN
339  617.2  602.2    3.8  12.9  15.5  15.5  32.9   49.4       NaN
340  616.5  623.2    5.0   9.2  18.4  18.4  26.9   40.3       NaN

[341 rows x 9 columns]

### Question 6: Time Check

In [27]:
#You are given a dataset, dataset-2.csv, containing columns id, id_2, and timestamp (startDay, startTime, endDay, endTime). 
#The goal is to verify the completeness of the time data by checking whether the timestamps for each unique 
#(id, id_2) pair cover a full 24-hour period (from 12:00:00 AM to 11:59:59 PM) and span all 7 days of the week 
#(from Monday to Sunday).

#Create a function that accepts dataset-2.csv as a DataFrame and returns a boolean series that indicates if each (id, id_2)
#pair has incorrect timestamps. The boolean series must have multi-index (id, id_2).